{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'Mapping' from 'collections' (/home/codespace/.python/current/lib/python3.10/collections/__init__.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39marcgis\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mgis\u001b[39;00m \u001b[39mimport\u001b[39;00m GIS\n\u001b[1;32m      2\u001b[0m \u001b[39m# Create a GIS object, as an anonymous user for this example\u001b[39;00m\n\u001b[1;32m      3\u001b[0m gis \u001b[39m=\u001b[39m GIS()\n",
      "File \u001b[0;32m~/.python/current/lib/python3.10/site-packages/arcgis/__init__.py:3\u001b[0m\n\u001b[1;32m      1\u001b[0m __version__ \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39m1.8.0\u001b[39m\u001b[39m'\u001b[39m\n\u001b[0;32m----> 3\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m \u001b[39mimport\u001b[39;00m (features, geoanalytics, geocoding, geometry)\n\u001b[1;32m      4\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m \u001b[39mimport\u001b[39;00m (geoprocessing, network, raster, realtime, schematics)\n\u001b[1;32m      5\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m \u001b[39mimport\u001b[39;00m (mapping, apps, learn)\n",
      "File \u001b[0;32m~/.python/current/lib/python3.10/site-packages/arcgis/features/__init__.py:21\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39mThe arcgis.features module contains types and functions for working with features and feature layers in the GIS.\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     18\u001b[0m \u001b[39mrepresentation and user experience - on a map, in a 3D scene, as entities with a property sheet or popups.\u001b[39;00m\n\u001b[1;32m     19\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m---> 21\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mfeature\u001b[39;00m \u001b[39mimport\u001b[39;00m Feature, FeatureSet, FeatureCollection\n\u001b[1;32m     22\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mlayer\u001b[39;00m \u001b[39mimport\u001b[39;00m FeatureLayer, Table, FeatureLayerCollection\n\u001b[1;32m     23\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39m_data\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mgeodataset\u001b[39;00m \u001b[39mimport\u001b[39;00m SpatialDataFrame\n",
      "File \u001b[0;32m~/.python/current/lib/python3.10/site-packages/arcgis/features/feature.py:12\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39muuid\u001b[39;00m\n\u001b[1;32m     11\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mdatetime\u001b[39;00m \u001b[39mimport\u001b[39;00m datetime\n\u001b[0;32m---> 12\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39marcgis\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_impl\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcommon\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_mixins\u001b[39;00m \u001b[39mimport\u001b[39;00m PropertyMap\n\u001b[1;32m     13\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39marcgis\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_impl\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcommon\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_spatial\u001b[39;00m \u001b[39mimport\u001b[39;00m json_to_featureclass\n\u001b[1;32m     14\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39marcgis\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_impl\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcommon\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_utils\u001b[39;00m \u001b[39mimport\u001b[39;00m _date_handler\n",
      "File \u001b[0;32m~/.python/current/lib/python3.10/site-packages/arcgis/_impl/common/_mixins.py:8\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39mMixin Classes for Attr-support.\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \n\u001b[1;32m      4\u001b[0m \u001b[39mCopyright (c) 2013 Brendan Curran-Johnson\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[39mhttps://github.com/bcj/AttrDict\u001b[39;00m\n\u001b[1;32m      6\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mabc\u001b[39;00m \u001b[39mimport\u001b[39;00m ABCMeta, abstractmethod\n\u001b[0;32m----> 8\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mcollections\u001b[39;00m \u001b[39mimport\u001b[39;00m Mapping, MutableMapping, Sequence, OrderedDict\n\u001b[1;32m      9\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mre\u001b[39;00m\n\u001b[1;32m     10\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mjson\u001b[39;00m\n",
      "\u001b[0;31mImportError\u001b[0m: cannot import name 'Mapping' from 'collections' (/home/codespace/.python/current/lib/python3.10/collections/__init__.py)"
     ]
    }
   ],
   "source": [
    "from arcgis.gis import GIS\n",
    "# Create a GIS object, as an anonymous user for this example\n",
    "gis = GIS()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: arcgis in /usr/local/python/3.10.4/lib/python3.10/site-packages (1.8.0)\n",
      "Collecting arcgis\n",
      "  Using cached arcgis-2.0.0.tar.gz (3.7 MB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting urllib3<1.26.0,>=1.25.10\n",
      "  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)\n",
      "Collecting cachetools\n",
      "  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)\n",
      "Requirement already satisfied: six in /home/codespace/.local/lib/python3.10/site-packages (from arcgis) (1.16.0)\n",
      "Collecting lxml\n",
      "  Using cached lxml-4.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)\n",
      "Requirement already satisfied: cryptography in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (39.0.2)\n",
      "Requirement already satisfied: ipywidgets>=7 in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (8.0.4)\n",
      "Requirement already satisfied: widgetsnbextension>=3 in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (4.0.5)\n",
      "Requirement already satisfied: pandas>=1 in /home/codespace/.local/lib/python3.10/site-packages (from arcgis) (1.5.3)\n",
      "Requirement already satisfied: numpy>=1.16.2 in /home/codespace/.local/lib/python3.10/site-packages (from arcgis) (1.24.2)\n",
      "Requirement already satisfied: matplotlib in /home/codespace/.local/lib/python3.10/site-packages (from arcgis) (3.7.0)\n",
      "Collecting keyring<=21.8.*,>=19\n",
      "  Using cached keyring-21.7.0-py3-none-any.whl (32 kB)\n",
      "Requirement already satisfied: lerc in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (0.1.0)\n",
      "Collecting ujson>=3\n",
      "  Using cached ujson-5.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (52 kB)\n",
      "Requirement already satisfied: jupyterlab in /home/codespace/.local/lib/python3.10/site-packages (from arcgis) (3.6.1)\n",
      "Collecting python-certifi-win32\n",
      "  Using cached python_certifi_win32-1.6.1-py2.py3-none-any.whl (7.3 kB)\n",
      "Requirement already satisfied: pyshp>=2 in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (2.3.1)\n",
      "Collecting geomet\n",
      "  Using cached geomet-1.0.0-py3-none-any.whl (28 kB)\n",
      "Requirement already satisfied: requests in /home/codespace/.local/lib/python3.10/site-packages (from arcgis) (2.28.2)\n",
      "Requirement already satisfied: requests-oauthlib in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (1.3.1)\n",
      "Requirement already satisfied: requests_toolbelt in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (0.10.1)\n",
      "Requirement already satisfied: requests_ntlm in /usr/local/python/3.10.4/lib/python3.10/site-packages (from arcgis) (1.2.0)\n",
      "Collecting requests-gssapi\n",
      "  Using cached requests_gssapi-1.2.3-py2.py3-none-any.whl\n",
      "Requirement already satisfied: traitlets>=4.3.1 in /home/codespace/.local/lib/python3.10/site-packages (from ipywidgets>=7->arcgis) (5.9.0)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /home/codespace/.local/lib/python3.10/site-packages (from ipywidgets>=7->arcgis) (6.21.2)\n",
      "Requirement already satisfied: jupyterlab-widgets~=3.0 in /usr/local/python/3.10.4/lib/python3.10/site-packages (from ipywidgets>=7->arcgis) (3.0.5)\n",
      "Requirement already satisfied: ipython>=6.1.0 in /home/codespace/.local/lib/python3.10/site-packages (from ipywidgets>=7->arcgis) (8.10.0)\n",
      "Requirement already satisfied: jeepney>=0.4.2 in /usr/local/python/3.10.4/lib/python3.10/site-packages (from keyring<=21.8.*,>=19->arcgis) (0.8.0)\n",
      "Requirement already satisfied: SecretStorage>=3.2 in /usr/local/python/3.10.4/lib/python3.10/site-packages (from keyring<=21.8.*,>=19->arcgis) (3.3.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=1->arcgis) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas>=1->arcgis) (2022.7.1)\n",
      "Requirement already satisfied: cffi>=1.12 in /home/codespace/.local/lib/python3.10/site-packages (from cryptography->arcgis) (1.15.1)\n",
      "Requirement already satisfied: click in /home/codespace/.local/lib/python3.10/site-packages (from geomet->arcgis) (8.1.3)\n",
      "Requirement already satisfied: tomli in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (2.0.1)\n",
      "Requirement already satisfied: notebook<7 in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (6.5.2)\n",
      "Requirement already satisfied: nbclassic in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (0.5.1)\n",
      "Requirement already satisfied: jupyter-core in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (5.2.0)\n",
      "Requirement already satisfied: jinja2>=2.1 in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (3.1.2)\n",
      "Requirement already satisfied: packaging in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (23.0)\n",
      "Requirement already satisfied: jupyter-server-ydoc<0.7.0,>=0.6.0 in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (0.6.1)\n",
      "Requirement already satisfied: tornado>=6.1.0 in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (6.2)\n",
      "Requirement already satisfied: jupyterlab-server~=2.19 in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (2.19.0)\n",
      "Requirement already satisfied: jupyter-ydoc~=0.2.2 in /home/codespace/.local/lib/python3.10/site-packages (from jupyterlab->arcgis) (0.2.2)\n",
      "Requirement already satisfied: jupyter-server<3,>=1.16.0 in /usr/local/python/3.10.4/lib/python3.10/site-packages (from jupyterlab->arcgis) (1.23.6)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->arcgis) (1.4.4)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->arcgis) (4.38.0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->arcgis) (1.0.7)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->arcgis) (9.4.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->arcgis) (0.11.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->arcgis) (3.0.9)\n",
      "Collecting setuptools-scm\n",
      "  Using cached setuptools_scm-7.1.0-py3-none-any.whl (43 kB)\n",
      "Requirement already satisfied: wrapt>=1.10.4 in /home/codespace/.local/lib/python3.10/site-packages (from python-certifi-win32->arcgis) (1.15.0)\n",
      "Requirement already satisfied: certifi in /home/codespace/.local/lib/python3.10/site-packages (from python-certifi-win32->arcgis) (2022.12.7)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests->arcgis) (3.0.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests->arcgis) (3.4)\n",
      "Collecting gssapi\n",
      "  Using cached gssapi-1.8.2.tar.gz (94 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[21 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m /bin/sh: 1: krb5-config: not found\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/home/codespace/.python/current/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/home/codespace/.python/current/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m   File \"/home/codespace/.python/current/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 118, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return hook(config_settings)\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-ge4drn6k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 338, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return self._get_build_requires(config_settings, requirements=['wheel'])\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-ge4drn6k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 320, in _get_build_requires\n",
      "  \u001b[31m   \u001b[0m     self.run_setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-ge4drn6k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 335, in run_setup\n",
      "  \u001b[31m   \u001b[0m     exec(code, locals())\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 109, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 22, in get_output\n",
      "  \u001b[31m   \u001b[0m   File \"/home/codespace/.python/current/lib/python3.10/subprocess.py\", line 420, in check_output\n",
      "  \u001b[31m   \u001b[0m     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n",
      "  \u001b[31m   \u001b[0m   File \"/home/codespace/.python/current/lib/python3.10/subprocess.py\", line 524, in run\n",
      "  \u001b[31m   \u001b[0m     raise CalledProcessError(retcode, process.args,\n",
      "  \u001b[31m   \u001b[0m subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "\u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install arcgis --upgrade"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Package                  Version\n",
      "------------------------ ----------\n",
      "aiofiles                 22.1.0\n",
      "aiosqlite                0.18.0\n",
      "anyio                    3.6.2\n",
      "arcgis                   1.8.0\n",
      "argon2-cffi              21.3.0\n",
      "argon2-cffi-bindings     21.2.0\n",
      "arrow                    1.2.3\n",
      "astroid                  2.14.2\n",
      "asttokens                2.2.1\n",
      "attrs                    22.2.0\n",
      "Babel                    2.11.0\n",
      "backcall                 0.2.0\n",
      "beautifulsoup4           4.11.2\n",
      "black                    23.1.0\n",
      "bleach                   6.0.0\n",
      "certifi                  2022.12.7\n",
      "cffi                     1.15.1\n",
      "charset-normalizer       3.0.1\n",
      "click                    8.1.3\n",
      "colorama                 0.4.6\n",
      "comm                     0.1.2\n",
      "contourpy                1.0.7\n",
      "cryptography             39.0.2\n",
      "cycler                   0.11.0\n",
      "debugpy                  1.6.6\n",
      "decorator                5.1.1\n",
      "defusedxml               0.7.1\n",
      "dill                     0.3.6\n",
      "entrypoints              0.4\n",
      "exceptiongroup           1.1.0\n",
      "executing                1.2.0\n",
      "fastjsonschema           2.16.2\n",
      "fonttools                4.38.0\n",
      "fqdn                     1.5.1\n",
      "gitdb                    4.0.10\n",
      "GitPython                3.1.30\n",
      "idna                     3.4\n",
      "importlib-metadata       6.0.0\n",
      "iniconfig                2.0.0\n",
      "ipykernel                6.21.2\n",
      "ipython                  8.10.0\n",
      "ipython-genutils         0.2.0\n",
      "ipywidgets               8.0.4\n",
      "isoduration              20.11.0\n",
      "isort                    5.12.0\n",
      "jaraco.classes           3.2.3\n",
      "jedi                     0.18.2\n",
      "jeepney                  0.8.0\n",
      "Jinja2                   3.1.2\n",
      "joblib                   1.2.0\n",
      "json5                    0.9.11\n",
      "jsonpointer              2.3\n",
      "jsonschema               4.17.3\n",
      "jupyter_client           7.4.1\n",
      "jupyter_core             5.2.0\n",
      "jupyter-events           0.5.0\n",
      "jupyter-server           1.23.6\n",
      "jupyter_server_fileid    0.6.0\n",
      "jupyter-server-mathjax   0.2.6\n",
      "jupyter_server_terminals 0.4.4\n",
      "jupyter_server_ydoc      0.6.1\n",
      "jupyter-ydoc             0.2.2\n",
      "jupyterlab               3.6.1\n",
      "jupyterlab-git           0.41.0\n",
      "jupyterlab-pygments      0.2.2\n",
      "jupyterlab_server        2.19.0\n",
      "jupyterlab-widgets       3.0.5\n",
      "keyring                  23.13.1\n",
      "kiwisolver               1.4.4\n",
      "lazy-object-proxy        1.9.0\n",
      "lerc                     0.1.0\n",
      "MarkupSafe               2.1.2\n",
      "matplotlib               3.7.0\n",
      "matplotlib-inline        0.1.6\n",
      "mccabe                   0.7.0\n",
      "mistune                  2.0.5\n",
      "more-itertools           9.1.0\n",
      "mypy-extensions          1.0.0\n",
      "nbclassic                0.5.1\n",
      "nbclient                 0.7.2\n",
      "nbconvert                7.2.9\n",
      "nbdime                   3.1.1\n",
      "nbformat                 5.7.3\n",
      "nest-asyncio             1.5.6\n",
      "notebook                 6.5.2\n",
      "notebook_shim            0.2.2\n",
      "numpy                    1.24.2\n",
      "nvidia-cublas-cu11       11.10.3.66\n",
      "nvidia-cuda-nvrtc-cu11   11.7.99\n",
      "nvidia-cuda-runtime-cu11 11.7.99\n",
      "nvidia-cudnn-cu11        8.5.0.96\n",
      "oauthlib                 3.2.2\n",
      "packaging                23.0\n",
      "pandas                   1.5.3\n",
      "pandocfilters            1.5.0\n",
      "parso                    0.8.3\n",
      "pathspec                 0.11.0\n",
      "pexpect                  4.8.0\n",
      "pickleshare              0.7.5\n",
      "Pillow                   9.4.0\n",
      "pip                      23.0.1\n",
      "platformdirs             3.0.0\n",
      "plotly                   5.13.0\n",
      "pluggy                   1.0.0\n",
      "prometheus-client        0.16.0\n",
      "prompt-toolkit           3.0.36\n",
      "psutil                   5.9.4\n",
      "ptyprocess               0.7.0\n",
      "pure-eval                0.2.2\n",
      "pycparser                2.21\n",
      "Pygments                 2.14.0\n",
      "pylint                   2.16.2\n",
      "pyparsing                3.0.9\n",
      "pyrsistent               0.19.3\n",
      "pyshp                    2.3.1\n",
      "pyspnego                 0.8.0\n",
      "pytest                   7.2.1\n",
      "python-dateutil          2.8.2\n",
      "python-json-logger       2.0.6\n",
      "pytz                     2022.7.1\n",
      "PyYAML                   6.0\n",
      "pyzmq                    25.0.0\n",
      "requests                 2.28.2\n",
      "requests-ntlm            1.2.0\n",
      "requests-oauthlib        1.3.1\n",
      "requests-toolbelt        0.10.1\n",
      "rfc3339-validator        0.1.4\n",
      "rfc3986-validator        0.1.1\n",
      "scikit-learn             1.2.1\n",
      "scipy                    1.10.0\n",
      "seaborn                  0.12.2\n",
      "SecretStorage            3.3.3\n",
      "Send2Trash               1.8.0\n",
      "setuptools               58.1.0\n",
      "six                      1.16.0\n",
      "smmap                    5.0.0\n",
      "sniffio                  1.3.0\n",
      "soupsieve                2.4\n",
      "stack-data               0.6.2\n",
      "tenacity                 8.2.1\n",
      "terminado                0.17.1\n",
      "threadpoolctl            3.1.0\n",
      "tinycss2                 1.2.1\n",
      "tomli                    2.0.1\n",
      "tomlkit                  0.11.6\n",
      "torch                    1.13.1\n",
      "tornado                  6.2\n",
      "traitlets                5.9.0\n",
      "typing_extensions        4.5.0\n",
      "uri-template             1.2.0\n",
      "urllib3                  1.26.14\n",
      "voila                    0.4.0\n",
      "wcwidth                  0.2.6\n",
      "webcolors                1.12\n",
      "webencodings             0.5.1\n",
      "websocket-client         1.5.1\n",
      "websockets               10.4\n",
      "wheel                    0.38.4\n",
      "widgetsnbextension       4.0.5\n",
      "wrapt                    1.15.0\n",
      "y-py                     0.5.5\n",
      "ypy-websocket            0.8.2\n",
      "zipp                     3.15.0\n"
     ]
    }
   ],
   "source": [
    "!pip list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Add a layer to the map\n",
    "layer = gis.content.search('title: USA States')[0]\n",
    "map.add_layer(layer)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
